"""pages rendered with javascript

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-02 07:23:09.608444
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_pages', sa.Column('rendered_with_js', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_pages', 'rendered_with_js')
    # ### end Alembic commands ###
