"""plans

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-29 20:44:10.131802
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('key', name=op.f('uq_plans_key'))
    )
    op.create_index(
        'uq_plans_single_default', 'plans', ['is_default'], unique=True,
        postgresql_where=sa.text('is_default'),
    )
    # Seed plans. Internal has no limits and is the default, so existing organisations
    # (including NIIT) keep working exactly as before. The others are examples whose
    # numbers the owner is expected to set; there are no prices.
    plans = sa.table(
        'plans',
        sa.column('id', sa.Uuid()),
        sa.column('key', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('limits', postgresql.JSONB()),
        sa.column('is_default', sa.Boolean()),
    )
    op.bulk_insert(plans, [
        {'id': uuid.uuid4(), 'key': 'internal', 'name': 'Internal', 'is_default': True,
         'description': 'No plan limits. Platform crawl caps still apply.', 'limits': {}},
        {'id': uuid.uuid4(), 'key': 'starter', 'name': 'Starter', 'is_default': False,
         'description': 'Example limits for a small site.',
         'limits': {'max_projects': 1, 'max_members': 3, 'max_pages_per_crawl': 500,
                    'max_crawls_per_month': 8, 'max_ai_tasks_per_day': 20,
                    'max_reports_per_month': 10}},
        {'id': uuid.uuid4(), 'key': 'professional', 'name': 'Professional', 'is_default': False,
         'description': 'Example limits for several sites.',
         'limits': {'max_projects': 10, 'max_members': 15, 'max_pages_per_crawl': 5000,
                    'max_crawls_per_month': 60, 'max_ai_tasks_per_day': 200,
                    'max_reports_per_month': 60}},
    ])
    op.add_column('organisations', sa.Column('plan_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_organisations_plan_id'), 'organisations', ['plan_id'], unique=False)
    op.create_foreign_key(op.f('fk_organisations_plan_id_plans'), 'organisations', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_organisations_plan_id_plans'), 'organisations', type_='foreignkey')
    op.drop_index(op.f('ix_organisations_plan_id'), table_name='organisations')
    op.drop_column('organisations', 'plan_id')
    op.drop_index('uq_plans_single_default', table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
