"""search console data

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-02 07:04:48.737110
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_page_days',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('page', sa.String(length=2048), nullable=False),
    sa.Column('page_host', sa.String(length=253), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_search_page_days_integration_id_integrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_search_page_days_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_page_days'))
    )
    op.create_index('ix_search_page_days_integration_day', 'search_page_days', ['integration_id', 'day'], unique=False)
    op.create_index('ix_search_page_days_scope', 'search_page_days', ['organisation_id', 'page_host', 'day'], unique=False)
    op.create_table('search_syncs',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='search_sync_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('page_day_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('query_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_search_syncs_integration_id_integrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_search_syncs_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_search_syncs_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_syncs'))
    )
    op.create_index(op.f('ix_search_syncs_integration_id'), 'search_syncs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_search_syncs_organisation_id'), 'search_syncs', ['organisation_id'], unique=False)
    op.create_index('ix_search_syncs_status_created', 'search_syncs', ['status', 'created_at'], unique=False)
    op.create_table('search_page_queries',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('sync_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.String(length=2048), nullable=False),
    sa.Column('page_host', sa.String(length=253), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_search_page_queries_integration_id_integrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_search_page_queries_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['search_syncs.id'], name=op.f('fk_search_page_queries_sync_id_search_syncs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_page_queries'))
    )
    op.create_index('ix_search_page_queries_integration', 'search_page_queries', ['integration_id'], unique=False)
    op.create_index('ix_search_page_queries_scope', 'search_page_queries', ['organisation_id', 'page_host'], unique=False)
    op.create_index(op.f('ix_search_page_queries_sync_id'), 'search_page_queries', ['sync_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_page_queries_sync_id'), table_name='search_page_queries')
    op.drop_index('ix_search_page_queries_scope', table_name='search_page_queries')
    op.drop_index('ix_search_page_queries_integration', table_name='search_page_queries')
    op.drop_table('search_page_queries')
    op.drop_index('ix_search_syncs_status_created', table_name='search_syncs')
    op.drop_index(op.f('ix_search_syncs_organisation_id'), table_name='search_syncs')
    op.drop_index(op.f('ix_search_syncs_integration_id'), table_name='search_syncs')
    op.drop_table('search_syncs')
    op.drop_index('ix_search_page_days_scope', table_name='search_page_days')
    op.drop_index('ix_search_page_days_integration_day', table_name='search_page_days')
    op.drop_table('search_page_days')
    # ### end Alembic commands ###
