"""ai feedback

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-02 06:50:01.465329
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('ai_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Enum('helpful', 'not_helpful', name='feedback_rating', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.Enum('wrong', 'off_topic', 'vague', 'missed_data', 'other', name='feedback_reason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_analyses.id'], name=op.f('fk_ai_feedback_ai_analysis_id_ai_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ai_feedback_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback')),
    sa.UniqueConstraint('ai_analysis_id', 'user_id', name=op.f('uq_ai_feedback_ai_analysis_id'))
    )
    op.create_index(op.f('ix_ai_feedback_ai_analysis_id'), 'ai_feedback', ['ai_analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_organisation_id'), 'ai_feedback', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedback_organisation_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_ai_analysis_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    # ### end Alembic commands ###
