"""reports and crawl schedules

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-29 20:06:05.441603
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_schedules',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', name='schedule_frequency', native_enum=False, create_constraint=True, length=16), server_default='weekly', nullable=False),
    sa.Column('hour', sa.Integer(), server_default='2', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_crawl_schedules_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_crawl_schedules_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_crawl_schedules_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_schedules')),
    sa.UniqueConstraint('project_id', name=op.f('uq_crawl_schedules_project_id'))
    )
    op.create_index(op.f('ix_crawl_schedules_next_run_at'), 'crawl_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_crawl_schedules_organisation_id'), 'crawl_schedules', ['organisation_id'], unique=False)
    op.create_table('reports',
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('crawl_job_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='report_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('include_ai', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('pdf', sa.LargeBinary(), nullable=True),
    sa.Column('pdf_status', sa.Enum('pending', 'ready', 'unavailable', 'failed', name='pdf_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('pdf_error', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], name=op.f('fk_reports_crawl_job_id_crawl_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_reports_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_reports_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_organisation_id'), 'reports', ['organisation_id'], unique=False)
    op.create_index('ix_reports_project_created', 'reports', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_status_created', table_name='reports')
    op.drop_index('ix_reports_project_created', table_name='reports')
    op.drop_index(op.f('ix_reports_organisation_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_crawl_schedules_organisation_id'), table_name='crawl_schedules')
    op.drop_index(op.f('ix_crawl_schedules_next_run_at'), table_name='crawl_schedules')
    op.drop_table('crawl_schedules')
    # ### end Alembic commands ###
